### PR TITLE
Transition to federated plugin. 

### PR DESCRIPTION
**Pull request by Piero512**
Hey, I was interested in transitioning the plugin into a federated plugin and this is a first attempt. 

I welcome comments and reviews. 

There is a huge problem right now, and that is that the base class is not federation-friendly. I want to explore attempts to refactor the code without much breakage.

### CODE REVIEW

**Comment by Piero512** [comment]
I think I did an okay job, but I am open to suggestions. I'm no good at working out tests, but the example project works just fine on iOS.

**Comment by Piero512** [comment]
Right now I am writing some code against the platform interface and I kinda find annoying to have to serialize and deserialize services and stuff, to be able to keep up with the fromJSON eventStreams that are retrieved from the  from the channels. I think it would be best if we make the Platform Interface simpler by receiving the Discovery and Broadcast classes on different methods 🤔

**Comment by Piero512** [comment]
@Skyost I think this API is working great

**Comment by Skyost** [comment]
That's okay, I'm a little bit busy currently because of my studies, but I will test it next week.

**Comment by Piero512** [comment]
I have made public a Linux implementation you might check down on how the platform interface is used at https://github.com/Piero512/bonsoir_linux_dbus that uses the platform interface in this pull request.

**Comment by Skyost** [comment]
I've merged it. I'm currently testing it, and I have one question @Piero512 : is it legal for `bonsoir_platform_interface` to depend on `bonsoir` ? Because I've never encountered this in all federated plugin implementations I've seen so far.

**Comment by Piero512** [comment]
I've been thinking about the same thing but wasn't sure how to proceed. It
is possible to move the classes that are used from the Bonsoir pkg to the
platform interface and just export again the public platform interface in
bonsoir/bonsoir.dart to break the dependency cycle. This should keep the
regular API surface intact.

**Comment by Skyost** [comment]
@Piero512 Good idea !

**Comment by Skyost** [comment]
I think it should be good now. What do you think about it ?

**Comment by Piero512** [comment]
Now the next step is to start publishing the packages to pub.dev I think so that future (and current) implementations can depend on their specific version.

**Comment by Piero512** [comment]
Okay, well, I have some thoughts. I had to manually import the definitions of service, and broadcast from their respective source file in the platform package. It would be great if those definitions (the ones moved from Bonsoir to bonsoir_platform_interface), were exported by the bonsoir_platform_interface.dart file directly, since they're required for the platform interface to be fully defined in platform implementations. I think that if you export those definitions they're automatically imported in the file, if not, well, some rearranging might do.

**Comment by Skyost** [comment]
Okay, I will do some refactoring.

**Pull request merged**
